/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tjframes;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Igor
 */
public class jfIgor extends javax.swing.JFrame {

    /**
     * Creates new form jfIgor
     */
    public jfIgor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jtfIdade2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jbCalcDias2 = new javax.swing.JButton();
        jtfResultado2 = new javax.swing.JTextField();
        jlResultado2 = new javax.swing.JLabel();
        jtfSomTexto2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfValor2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jrdbKm2m2 = new javax.swing.JRadioButton();
        jrdbM2Km2 = new javax.swing.JRadioButton();
        jbConverter2 = new javax.swing.JButton();
        jcbEstCivil2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jbEstCivil2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jcbFutebol2 = new javax.swing.JCheckBox();
        jcbVolei2 = new javax.swing.JCheckBox();
        jcbBasquete2 = new javax.swing.JCheckBox();
        jbEsportes2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaEsportes2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtfIdade2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtfIdade2.setName("jtfIdade"); // NOI18N
        jtfIdade2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfIdade2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIdade2KeyTyped(evt);
            }
        });

        jLabel11.setText("Idade:");
        jLabel11.setName(""); // NOI18N

        jbCalcDias2.setText("Calcular Dias");
        jbCalcDias2.setName("jbCalcDias"); // NOI18N
        jbCalcDias2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcDias2ActionPerformed(evt);
            }
        });

        jtfResultado2.setEditable(false);
        jtfResultado2.setName("jtfResultado"); // NOI18N

        jlResultado2.setText("Resultado:");

        jtfSomTexto2.setName("jtfSomTexto"); // NOI18N
        jtfSomTexto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSomTexto2KeyTyped(evt);
            }
        });

        jLabel12.setText("Somente Texto");

        jtfValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfValor2KeyTyped(evt);
            }
        });

        jLabel13.setText("Valor");

        jrdbKm2m2.setText("de Km para Milhas");

        jrdbM2Km2.setText("de Milhas para Km");

        jbConverter2.setText("Converter");
        jbConverter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConverter2ActionPerformed(evt);
            }
        });

        jcbEstCivil2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Solteiro (a)", "Casado (a)", "Divorciado (a)", "Viuvo (a)", "Amizade Colorida kkkk" }));

        jLabel14.setText("Estado Civil");

        jbEstCivil2.setText("Estado Civil?");
        jbEstCivil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEstCivil2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Quais esportes vc pratica?");

        jcbFutebol2.setText("Futebol");
        jcbFutebol2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbFutebol2ItemStateChanged(evt);
            }
        });

        jcbVolei2.setText("Vôlei");
        jcbVolei2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbVolei2ItemStateChanged(evt);
            }
        });

        jcbBasquete2.setText("Basquete");
        jcbBasquete2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbBasquete2ItemStateChanged(evt);
            }
        });

        jbEsportes2.setText("Listar");
        jbEsportes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEsportes2ActionPerformed(evt);
            }
        });

        jtaEsportes2.setEditable(false);
        jtaEsportes2.setColumns(20);
        jtaEsportes2.setRows(5);
        jScrollPane4.setViewportView(jtaEsportes2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbEstCivil2)
                            .addComponent(jbCalcDias2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlResultado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbEstCivil2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfSomTexto2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfResultado2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfIdade2, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfValor2))
                            .addComponent(jrdbKm2m2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrdbM2Km2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbConverter2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbFutebol2)
                                    .addComponent(jcbVolei2)
                                    .addComponent(jcbBasquete2)
                                    .addComponent(jbEsportes2))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIdade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jtfValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlResultado2)
                    .addComponent(jrdbKm2m2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSomTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jrdbM2Km2))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCalcDias2)
                    .addComponent(jbConverter2))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbEstCivil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbEstCivil2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jcbFutebol2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbVolei2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbBasquete2))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbEsportes2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIdade2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdade2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.jbCalcDias.doClick();
        }
    }//GEN-LAST:event_jtfIdade2KeyPressed

    private void jtfIdade2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdade2KeyTyped
        // TODO add your handling code here:
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Somente números!");
        }
    }//GEN-LAST:event_jtfIdade2KeyTyped

    private void jbCalcDias2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcDias2ActionPerformed
        // TODO add your handling code here:
        if (jtfIdade.getText().equals("")) {
            jtfResultado.setForeground(Color.red);
            jtfResultado.setText("Idade vazia");
        } else {
            int idade = Integer.parseInt(jtfIdade.getText());
            int dias = idade * 365;

            jtfResultado.setForeground(Color.BLACK);
            jtfResultado.setText(Integer.toString(dias));
            jtfIdade.setText("");
        }
        jtfIdade.requestFocus();
    }//GEN-LAST:event_jbCalcDias2ActionPerformed

    private void jtfSomTexto2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSomTexto2KeyTyped
        // Somente Texto
        String caracteres = "0123456789";
        if (caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfSomTexto2KeyTyped

    private void jtfValor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValor2KeyTyped
        // TODO add your handling code here:
        String caracteres = "0123456789.";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfValor2KeyTyped

    private void jbConverter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConverter2ActionPerformed
        // TODO add your handling code here:
        if (!jtfValor.getText().equals("")) {
            double result = 0;
            double valor = Double.parseDouble(jtfValor.getText());

            if (jrdbKm2m.isSelected()) {
                result = valor / 1.6;
            } else if (jrdbM2Km.isSelected()) {
                result = valor * 1.6;
            }
            JOptionPane.showMessageDialog(this, "O resulado é: "
                + NumberFormat.getInstance().format(result),
                "Conversão", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Valor não pode ser vazio");
            jtfValor.requestFocus();
        }
    }//GEN-LAST:event_jbConverter2ActionPerformed

    private void jbEstCivil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEstCivil2ActionPerformed
        // TODO add your handling code here:
        if (jcbEstCivil.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(this, "Nenhum estado civil selecionado!");
        } else {
            JOptionPane.showMessageDialog(this, "Estado Civil é "
                + jcbEstCivil.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jbEstCivil2ActionPerformed

    private void jcbFutebol2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbFutebol2ItemStateChanged
        // TODO add your handling code here:
        String esportes = jtaEsportes.getText();

        String texto = jcbFutebol.getText() + "\n";
        if (jcbFutebol.isSelected()) {
            jtaEsportes.setText(esportes + texto);
        } else {
            esportes = esportes.replace(texto, "");
            jtaEsportes.setText(esportes);
        }
    }//GEN-LAST:event_jcbFutebol2ItemStateChanged

    private void jcbVolei2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbVolei2ItemStateChanged
        // TODO add your handling code here:
        String esportes = jtaEsportes.getText();
        String texto = jcbVolei.getText() + "\n";

        if (jcbVolei.isSelected()) {
            jtaEsportes.setText(esportes + texto);
        } else {
            esportes = esportes.replace(texto, "");
            jtaEsportes.setText(esportes);
        }
    }//GEN-LAST:event_jcbVolei2ItemStateChanged

    private void jcbBasquete2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbBasquete2ItemStateChanged
        // TODO add your handling code here:
        String esportes = jtaEsportes.getText();
        String texto = jcbBasquete.getText() + "\n";

        if (jcbBasquete.isSelected()) {
            jtaEsportes.setText(esportes + texto);
        } else {
            esportes = esportes.replace(texto, "");
            jtaEsportes.setText(esportes);
        }
    }//GEN-LAST:event_jcbBasquete2ItemStateChanged

    private void jbEsportes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEsportes2ActionPerformed
        // TODO add your handling code here:
        String ep1 = "", ep2 = "", ep3 = "";
        if (jcbFutebol.isSelected()) {
            ep1 = jcbFutebol.getText() + "\n";
        }
        if (jcbVolei.isSelected()) {
            ep2 = jcbVolei.getText() + "\n";
        }
        if (jcbBasquete.isSelected()) {
            ep3 = jcbBasquete.getText() + "\n";
        }
        JOptionPane.showMessageDialog(this, "Esportes: \n"
            + ep1
            + ep2
            + ep3);
    }//GEN-LAST:event_jbEsportes2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfIgor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfIgor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfIgor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfIgor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfIgor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton jbCalcDias;
    private javax.swing.JButton jbCalcDias1;
    private javax.swing.JButton jbCalcDias2;
    private javax.swing.JButton jbCalcDias3;
    private javax.swing.JButton jbConverter;
    private javax.swing.JButton jbConverter1;
    private javax.swing.JButton jbConverter2;
    private javax.swing.JButton jbConverter3;
    private javax.swing.JButton jbEsportes;
    private javax.swing.JButton jbEsportes1;
    private javax.swing.JButton jbEsportes2;
    private javax.swing.JButton jbEsportes3;
    private javax.swing.JButton jbEstCivil;
    private javax.swing.JButton jbEstCivil1;
    private javax.swing.JButton jbEstCivil2;
    private javax.swing.JButton jbEstCivil3;
    private javax.swing.JCheckBox jcbBasquete;
    private javax.swing.JCheckBox jcbBasquete1;
    private javax.swing.JCheckBox jcbBasquete2;
    private javax.swing.JCheckBox jcbBasquete3;
    private javax.swing.JComboBox<String> jcbEstCivil;
    private javax.swing.JComboBox<String> jcbEstCivil1;
    private javax.swing.JComboBox<String> jcbEstCivil2;
    private javax.swing.JComboBox<String> jcbEstCivil3;
    private javax.swing.JCheckBox jcbFutebol;
    private javax.swing.JCheckBox jcbFutebol1;
    private javax.swing.JCheckBox jcbFutebol2;
    private javax.swing.JCheckBox jcbFutebol3;
    private javax.swing.JCheckBox jcbVolei;
    private javax.swing.JCheckBox jcbVolei1;
    private javax.swing.JCheckBox jcbVolei2;
    private javax.swing.JCheckBox jcbVolei3;
    private javax.swing.JLabel jlResultado;
    private javax.swing.JLabel jlResultado1;
    private javax.swing.JLabel jlResultado2;
    private javax.swing.JLabel jlResultado3;
    private javax.swing.JRadioButton jrdbKm2m;
    private javax.swing.JRadioButton jrdbKm2m1;
    private javax.swing.JRadioButton jrdbKm2m2;
    private javax.swing.JRadioButton jrdbKm2m3;
    private javax.swing.JRadioButton jrdbM2Km;
    private javax.swing.JRadioButton jrdbM2Km1;
    private javax.swing.JRadioButton jrdbM2Km2;
    private javax.swing.JRadioButton jrdbM2Km3;
    private javax.swing.JTextArea jtaEsportes;
    private javax.swing.JTextArea jtaEsportes1;
    private javax.swing.JTextArea jtaEsportes2;
    private javax.swing.JTextArea jtaEsportes3;
    private javax.swing.JTextField jtfIdade;
    private javax.swing.JTextField jtfIdade1;
    private javax.swing.JTextField jtfIdade2;
    private javax.swing.JTextField jtfIdade3;
    private javax.swing.JTextField jtfResultado;
    private javax.swing.JTextField jtfResultado1;
    private javax.swing.JTextField jtfResultado2;
    private javax.swing.JTextField jtfResultado3;
    private javax.swing.JTextField jtfSomTexto;
    private javax.swing.JTextField jtfSomTexto1;
    private javax.swing.JTextField jtfSomTexto2;
    private javax.swing.JTextField jtfSomTexto3;
    private javax.swing.JTextField jtfValor;
    private javax.swing.JTextField jtfValor1;
    private javax.swing.JTextField jtfValor2;
    private javax.swing.JTextField jtfValor3;
    // End of variables declaration//GEN-END:variables
}
