/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tjframes;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author wilian
 */
public class jfWilian extends javax.swing.JFrame {


    /**
     * Creates new form jfWilian
     */
    public jfWilian() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbKm2m = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelResultado = new javax.swing.JLabel();
        jbCalcDias = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfResultado = new javax.swing.JTextField();
        jtfidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtSoTexto = new javax.swing.JTextField();
        jrdbKm2m = new javax.swing.JRadioButton();
        jrdbM2km = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        ResultadoValor = new javax.swing.JTextField();
        jbConverter = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jcbEstadoCivil = new javax.swing.JComboBox<>();
        labelEstadoCivil = new javax.swing.JLabel();
        jbEstadoCivil = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtDiaSigno = new javax.swing.JTextField();
        jtMesSigno = new javax.swing.JTextField();
        jtResultadoSigno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jbGerarSigno = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jcbFutebol = new javax.swing.JCheckBox();
        jcbVolei = new javax.swing.JCheckBox();
        jcbBasquete = new javax.swing.JCheckBox();
        jtEsportes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaEsportes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wilian");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);

        jPanel1.setBackground(new java.awt.Color(90, 93, 95));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("Calculadora"); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Idade:");

        labelResultado.setBackground(new java.awt.Color(255, 255, 255));
        labelResultado.setForeground(new java.awt.Color(255, 255, 255));
        labelResultado.setText("  Resultado: ");

        jbCalcDias.setBackground(new java.awt.Color(90, 90, 90));
        jbCalcDias.setForeground(new java.awt.Color(255, 255, 255));
        jbCalcDias.setText("Calcular Dias");
        jbCalcDias.setName("jbCalcDias"); // NOI18N
        jbCalcDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcDiasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Calcule sua idade");

        jtfResultado.setEditable(false);
        jtfResultado.setBackground(new java.awt.Color(255, 255, 255));
        jtfResultado.setName("jtfIdade"); // NOI18N
        jtfResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfResultadoActionPerformed(evt);
            }
        });

        jtfidade.setBackground(new java.awt.Color(255, 255, 255));
        jtfidade.setName("jtfIdade"); // NOI18N
        jtfidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfidadeActionPerformed(evt);
            }
        });
        jtfidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfidadeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfidadeKeyTyped(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  Só Texto:");

        jtSoTexto.setBackground(new java.awt.Color(255, 255, 255));
        jtSoTexto.setForeground(new java.awt.Color(0, 0, 0));
        jtSoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSoTextoActionPerformed(evt);
            }
        });
        jtSoTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtSoTextoKeyTyped(evt);
            }
        });

        jrdbKm2m.setBackground(new java.awt.Color(90, 93, 95));
        rdbKm2m.add(jrdbKm2m);
        jrdbKm2m.setForeground(new java.awt.Color(255, 255, 255));
        jrdbKm2m.setSelected(true);
        jrdbKm2m.setText("de Km para Milhas");
        jrdbKm2m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdbKm2mActionPerformed(evt);
            }
        });

        jrdbM2km.setBackground(new java.awt.Color(90, 93, 95));
        rdbKm2m.add(jrdbM2km);
        jrdbM2km.setForeground(new java.awt.Color(255, 255, 255));
        jrdbM2km.setText("de Milhas para Km");
        jrdbM2km.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdbM2kmActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor:");

        ResultadoValor.setBackground(new java.awt.Color(255, 255, 255));
        ResultadoValor.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoValorActionPerformed(evt);
            }
        });
        ResultadoValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ResultadoValorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ResultadoValorKeyTyped(evt);
            }
        });

        jbConverter.setBackground(new java.awt.Color(90, 93, 95));
        jbConverter.setForeground(new java.awt.Color(255, 255, 255));
        jbConverter.setText("Converter");
        jbConverter.setToolTipText("");
        jbConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConverterActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Km para Milhas");

        jcbEstadoCivil.setBackground(new java.awt.Color(255, 255, 255));
        jcbEstadoCivil.setForeground(new java.awt.Color(0, 0, 0));
        jcbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)", "Amizade Colorida :p" }));
        jcbEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstadoCivilActionPerformed(evt);
            }
        });

        labelEstadoCivil.setBackground(new java.awt.Color(255, 255, 255));
        labelEstadoCivil.setForeground(new java.awt.Color(255, 255, 255));
        labelEstadoCivil.setText("Estado Civil :");

        jbEstadoCivil.setBackground(new java.awt.Color(90, 90, 90));
        jbEstadoCivil.setForeground(new java.awt.Color(255, 255, 255));
        jbEstadoCivil.setText("Estado Civil?");
        jbEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEstadoCivilActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        jNome.setForeground(new java.awt.Color(255, 255, 255));
        jNome.setText("Nome :");

        jtNome.setBackground(new java.awt.Color(255, 255, 255));
        jtNome.setForeground(new java.awt.Color(0, 0, 0));
        jtNome.setToolTipText("");
        jtNome.setName(""); // NOI18N
        jtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeActionPerformed(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNomeKeyTyped(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dia :");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Descubra seu Signo");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mês :");

        jtDiaSigno.setBackground(new java.awt.Color(255, 255, 255));
        jtDiaSigno.setForeground(new java.awt.Color(0, 0, 0));
        jtDiaSigno.setToolTipText("");
        jtDiaSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDiaSignoActionPerformed(evt);
            }
        });
        jtDiaSigno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDiaSignoKeyTyped(evt);
            }
        });

        jtMesSigno.setBackground(new java.awt.Color(255, 255, 255));
        jtMesSigno.setForeground(new java.awt.Color(0, 0, 0));
        jtMesSigno.setToolTipText("");
        jtMesSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMesSignoActionPerformed(evt);
            }
        });
        jtMesSigno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtMesSignoKeyTyped(evt);
            }
        });

        jtResultadoSigno.setEditable(false);
        jtResultadoSigno.setBackground(new java.awt.Color(255, 255, 255));
        jtResultadoSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtResultadoSignoActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Signo :");

        jbGerarSigno.setBackground(new java.awt.Color(90, 90, 90));
        jbGerarSigno.setForeground(new java.awt.Color(255, 255, 255));
        jbGerarSigno.setText("Gerar");
        jbGerarSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGerarSignoActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quais esportes você pratica ?");

        jcbFutebol.setBackground(new java.awt.Color(90, 93, 95));
        jcbFutebol.setForeground(new java.awt.Color(255, 255, 255));
        jcbFutebol.setText("Futebol");
        jcbFutebol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFutebolActionPerformed(evt);
            }
        });

        jcbVolei.setBackground(new java.awt.Color(90, 93, 95));
        jcbVolei.setForeground(new java.awt.Color(255, 255, 255));
        jcbVolei.setText("Vôlei");

        jcbBasquete.setBackground(new java.awt.Color(90, 93, 95));
        jcbBasquete.setForeground(new java.awt.Color(255, 255, 255));
        jcbBasquete.setText("Basquete");

        jtEsportes.setBackground(new java.awt.Color(90, 90, 90));
        jtEsportes.setForeground(new java.awt.Color(255, 255, 255));
        jtEsportes.setText("Listar");
        jtEsportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEsportesActionPerformed(evt);
            }
        });

        jtaEsportes.setEditable(false);
        jtaEsportes.setBackground(new java.awt.Color(255, 255, 255));
        jtaEsportes.setColumns(20);
        jtaEsportes.setForeground(new java.awt.Color(0, 0, 0));
        jtaEsportes.setLineWrap(true);
        jtaEsportes.setRows(5);
        jScrollPane1.setViewportView(jtaEsportes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelResultado)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbCalcDias, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addComponent(jtfidade)
                                .addComponent(jtSoTexto))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jrdbKm2m)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(ResultadoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jrdbM2km)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jbConverter))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator4)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelEstadoCivil)
                                .addGap(18, 18, 18)
                                .addComponent(jcbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbFutebol)
                                            .addComponent(jcbVolei)
                                            .addComponent(jcbBasquete))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                                .addComponent(jtDiaSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtMesSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jbGerarSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtResultadoSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(173, 173, 173)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(192, 192, 192)
                                        .addComponent(jbEstadoCivil)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jtEsportes)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(ResultadoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelResultado)
                            .addComponent(jrdbKm2m))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtSoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jrdbM2km))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbCalcDias)
                            .addComponent(jbConverter)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstadoCivil)
                    .addComponent(jNome)
                    .addComponent(jcbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jbEstadoCivil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtDiaSigno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtMesSigno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtResultadoSigno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbGerarSigno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jcbFutebol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbVolei)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbBasquete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jtEsportes))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCalcDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcDiasActionPerformed
        // TODO add your handling code here:

        if (jtfidade.getText().equals("")) {
            jtfResultado.setForeground(Color.red);
            jtfResultado.setText("Idade em branco!");
            JOptionPane.showMessageDialog(rootPane, "Idade não pode estár em branco!");
            jtfResultado.setText("");

        } else {
            int idade = Integer.parseInt(jtfidade.getText());
            int dias = idade * 365;
            if (dias < 1) {
                jtfResultado.setForeground(Color.red);
                jtfResultado.setText("Idade inválida!");
                jtfResultado.setText("");
            } else {
                jtfResultado.setForeground(Color.BLACK);
                jtfResultado.setText(NumberFormat.getInstance().format(dias));
                jtfidade.setText("");
            }
            jtfResultado.requestFocus();
        }
        //jtfResultado.setText(NumberFormat.getInstance().format(idade*365));
        //JOptionPane.showMessageDialog(this,"Sua idade em dias :"+ (idade *365));
    }//GEN-LAST:event_jbCalcDiasActionPerformed

    private void jtfResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfResultadoActionPerformed

    private void jtfidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfidadeActionPerformed

    private void jtfidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfidadeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            this.jbCalcDias.doClick();
        }
    }//GEN-LAST:event_jtfidadeKeyPressed

    private void jtfidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfidadeKeyTyped
        // TODO add your handling code here:
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();

        }
    }//GEN-LAST:event_jtfidadeKeyTyped

    private void jtSoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtSoTextoActionPerformed

    private void jtSoTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtSoTextoKeyTyped
        // TODO add your handling code here:
        String caracteres = "0123456789";
        if (caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();

        }
    }//GEN-LAST:event_jtSoTextoKeyTyped

    private void ResultadoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoValorActionPerformed

    private void jrdbKm2mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdbKm2mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdbKm2mActionPerformed

    private void jbConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConverterActionPerformed
        // TODO add your handling code here:
        if (!ResultadoValor.getText().equals("")) {
            double result = 0;
            double valor = Double.parseDouble(ResultadoValor.getText());
            if (jrdbKm2m.isSelected()) {
                result = valor / 1.6;
                ResultadoValor.setText("");
            } else if (jrdbM2km.isSelected()) {
                result = valor * 1.6;
                ResultadoValor.setText("");
            }
            JOptionPane.showMessageDialog(rootPane, "O resultado é: " + NumberFormat.getInstance().format(result), "Resultado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Valor não pode ser vazio!");
            ResultadoValor.requestFocus();

        }
    }//GEN-LAST:event_jbConverterActionPerformed

    private void ResultadoValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ResultadoValorKeyTyped
        // TODO add your handling code here:
        String caracteres = "0123456789.";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();

        }
    }//GEN-LAST:event_ResultadoValorKeyTyped

    private void jrdbM2kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdbM2kmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdbM2kmActionPerformed

    private void ResultadoValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ResultadoValorKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            this.jbConverter.doClick();
        }
    }//GEN-LAST:event_ResultadoValorKeyPressed

    private void jcbEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEstadoCivilActionPerformed

    private void jbEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEstadoCivilActionPerformed
        // TODO add your handling code here:
        if (jcbEstadoCivil.getSelectedItem().equals("Selecione") || (jtNome.getText().equals(""))) {
            JOptionPane.showMessageDialog(this, "Nome ou Estado Civil em branco!");
        } else {
            JOptionPane.showMessageDialog(this, jtNome.getText() + " Seu  Estado Civil é : " + jcbEstadoCivil.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jbEstadoCivilActionPerformed

    private void jtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyTyped
        // TODO add your handling code here:
        String caracteres = "0123456789";
        if (caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtNomeKeyTyped

    private void jtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeActionPerformed
        // TODO add your handling code here:
        if (jtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nome não pode estár em branco!");

        }
    }//GEN-LAST:event_jtNomeActionPerformed

    private void jbGerarSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGerarSignoActionPerformed
        // TODO add your handling code here:

        if (jtDiaSigno.getText().equals("") || jtMesSigno.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "dia ou mês invalido!");
        } else {
            int dia = Integer.parseInt(jtDiaSigno.getText());
            int mes = Integer.parseInt(jtMesSigno.getText());
            if ((dia >= 32 || dia <= 0) || (mes >= 13)) {
                JOptionPane.showMessageDialog(this, "dia ou mês invalido!");
                jtDiaSigno.setText("");
                jtMesSigno.setText("");
            } else if ((dia >= 21 && mes == 3) || (dia <= 20 && mes == 4)) {
                jtResultadoSigno.setForeground(Color.black);
                jtResultadoSigno.setText("  Áreis");
                jtDiaSigno.setText("");
                jtMesSigno.setText("");
            } else if ((dia >= 21 && mes == 4) || (dia <= 20 && mes == 5)) {
                jtResultadoSigno.setForeground(Color.black);
                jtResultadoSigno.setText(" Touro");
                jtDiaSigno.setText("");
                jtMesSigno.setText("");
            } else if ((dia >= 21 && mes == 5) || (dia <= 20 && mes == 6)) {
                jtResultadoSigno.setForeground(Color.black);
                jtResultadoSigno.setText("  Gêmeos ");
                jtDiaSigno.setText("");
                jtMesSigno.setText("");
            } else if ((dia >= 21 && mes == 6) || (dia <= 21 && mes == 7)) {
                jtResultadoSigno.setForeground(Color.black);
                jtResultadoSigno.setText(" Câncer");
                jtDiaSigno.setText("");
                jtMesSigno.setText("");
            } else if ((dia >= 22 && mes == 7) || (dia <= 22 && mes == 8)) {
                jtResultadoSigno.setForeground(Color.black);
                jtResultadoSigno.setText(" Leão");
                jtDiaSigno.setText("");
                jtMesSigno.setText("");
            } else if ((dia >= 23 && mes == 8) || (dia <= 22 && mes == 9)) {
                jtResultadoSigno.setForeground(Color.black);
                jtResultadoSigno.setText(" Virgem");
                jtDiaSigno.setText("");
                jtMesSigno.setText("");
            } else if ((dia >= 23 && mes == 9) || (dia <= 22 && mes == 10)) {
                jtResultadoSigno.setForeground(Color.black);
                jtResultadoSigno.setText("  Libra");
                jtDiaSigno.setText("");
                jtMesSigno.setText("");
            } else if ((dia >= 23 && mes == 10) || (dia <= 21 && mes == 11)) {
                jtResultadoSigno.setForeground(Color.black);
                jtResultadoSigno.setText(" Escorpião");
                jtDiaSigno.setText("");
                jtMesSigno.setText("");
            } else if ((dia >= 22 && mes == 11) || (dia <= 21 && mes == 12)) {
                jtResultadoSigno.setForeground(Color.black);
                jtResultadoSigno.setText(" Sagitário");
                jtDiaSigno.setText("");
                jtMesSigno.setText("");
            } else if ((dia >= 22 && mes == 12) || (dia <= 20 && mes == 1)) {
                jtResultadoSigno.setForeground(Color.black);
                jtResultadoSigno.setText(" Capricórnio");
                jtDiaSigno.setText("");
                jtMesSigno.setText("");
            } else if ((dia >= 21 && mes == 1) || (dia <= 19 && mes == 2)) {
                jtResultadoSigno.setForeground(Color.black);
                jtResultadoSigno.setText(" Aquário");
                jtDiaSigno.setText("");
                jtMesSigno.setText("");
            } else if ((dia >= 20 && mes == 2) || (dia <= 20 && mes == 3)) {
                jtResultadoSigno.setForeground(Color.black);
                jtResultadoSigno.setText(" Peixes");
                jtDiaSigno.setText("");
                jtMesSigno.setText("");
            }

        }
    }//GEN-LAST:event_jbGerarSignoActionPerformed

    private void jtMesSignoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMesSignoKeyTyped
        // TODO add your handling code here:
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtMesSignoKeyTyped

    private void jtDiaSignoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDiaSignoKeyTyped
        // TODO add your handling code here:
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtDiaSignoKeyTyped

    private void jtDiaSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDiaSignoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDiaSignoActionPerformed

    private void jtMesSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMesSignoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMesSignoActionPerformed

    private void jcbFutebolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFutebolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFutebolActionPerformed

    private void jtEsportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEsportesActionPerformed
        // TODO add your handling code here:
        if (jcbFutebol.isSelected() && jcbBasquete.isSelected() && jcbVolei.isSelected()) {
            jtaEsportes.setText("Futebol\nVôlei\nBasquete");

        } else if (jcbVolei.isSelected() && jcbBasquete.isSelected()) {
            jtaEsportes.setText("Vôlei\nBasquete");

        } else if (jcbBasquete.isSelected() && jcbFutebol.isSelected()) {
            jtaEsportes.setText("Futebol\nBasquete");

        } else if (jcbVolei.isSelected() && jcbFutebol.isSelected()) {
            jtaEsportes.setText("Futebol\nVôlei");

        } else if (jcbVolei.isSelected()) {
            jtaEsportes.setText("Vôlei");

        } else if (jcbBasquete.isSelected()) {
            jtaEsportes.setText("Basquete");

        } else if (jcbFutebol.isSelected()) {
            jtaEsportes.setText("Futebol");

        } else {
            JOptionPane.showMessageDialog(this, "Escolha algum esporte!");
            jtaEsportes.setText("");
        }
    }//GEN-LAST:event_jtEsportesActionPerformed

    private void jtResultadoSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtResultadoSignoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtResultadoSignoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfWilian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfWilian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfWilian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfWilian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfWilian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ResultadoValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton jbCalcDias;
    private javax.swing.JButton jbConverter;
    private javax.swing.JButton jbEstadoCivil;
    private javax.swing.JButton jbGerarSigno;
    private javax.swing.JCheckBox jcbBasquete;
    private javax.swing.JComboBox<String> jcbEstadoCivil;
    private javax.swing.JCheckBox jcbFutebol;
    private javax.swing.JCheckBox jcbVolei;
    private javax.swing.JRadioButton jrdbKm2m;
    private javax.swing.JRadioButton jrdbM2km;
    private javax.swing.JTextField jtDiaSigno;
    private javax.swing.JButton jtEsportes;
    private javax.swing.JTextField jtMesSigno;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtResultadoSigno;
    private javax.swing.JTextField jtSoTexto;
    private javax.swing.JTextArea jtaEsportes;
    private javax.swing.JTextField jtfResultado;
    private javax.swing.JTextField jtfidade;
    private javax.swing.JLabel labelEstadoCivil;
    private javax.swing.JLabel labelResultado;
    private javax.swing.ButtonGroup rdbKm2m;
    // End of variables declaration//GEN-END:variables


}
