/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.editora;
import model.livro;
import static tLivrariaOOJF.Main.cadEdi;
import static tLivrariaOOJF.Main.cadLiv;

/**
 *
 * @author Thiago Quevedo
 */
public class jfLivro extends javax.swing.JFrame {

    /**
     * Creates new form jfLivro
     */
    public jfLivro() {
        initComponents();
        this.addRowToTable();
        this.addItemEditora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jlAutor = new javax.swing.JLabel();
        jlIsbn = new javax.swing.JLabel();
        jtfTitulo = new javax.swing.JTextField();
        jlTitulo = new javax.swing.JLabel();
        jtfAutor = new javax.swing.JTextField();
        jtfIsbn = new javax.swing.JTextField();
        jbSalvar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLivros = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtfPreco = new javax.swing.JTextField();
        jlPreco = new javax.swing.JLabel();
        jlQntd = new javax.swing.JLabel();
        jtfQntd = new javax.swing.JTextField();
        jlAssunto = new javax.swing.JLabel();
        jtfAssunto = new javax.swing.JTextField();
        jcbEditora = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlAutor.setText("Autor:");

        jlIsbn.setText("ISBN:");

        jlTitulo.setText("Título:");

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");

        jtLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "ISBN", "Autor", "Assunto", "Qntd", "Editora", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Short.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtLivros.setToolTipText("");
        jScrollPane1.setViewportView(jtLivros);
        if (jtLivros.getColumnModel().getColumnCount() > 0) {
            jtLivros.getColumnModel().getColumn(0).setResizable(false);
            jtLivros.getColumnModel().getColumn(1).setResizable(false);
            jtLivros.getColumnModel().getColumn(2).setResizable(false);
            jtLivros.getColumnModel().getColumn(3).setResizable(false);
            jtLivros.getColumnModel().getColumn(4).setResizable(false);
            jtLivros.getColumnModel().getColumn(5).setResizable(false);
            jtLivros.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("sansserif", 2, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro de Livro");

        jlPreco.setText("Preço:");

        jlQntd.setText("Qntd:");

        jlAssunto.setText("Assunto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlTitulo)
                                    .addComponent(jlAutor))
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlIsbn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jlQntd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfQntd, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfIsbn)
                                    .addComponent(jcbEditora, 0, 150, Short.MAX_VALUE))
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlAssunto)
                                        .addGap(76, 76, 76)
                                        .addComponent(jtfAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(jlPreco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbCancelar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIsbn)
                    .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTitulo)
                    .addComponent(jtfIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAutor)
                    .addComponent(jtfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfQntd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQntd)
                    .addComponent(jcbEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAssunto)
                    .addComponent(jtfAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPreco)
                    .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbLimpar)
                    .addComponent(jbCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addRowToTable() {
        DefaultTableModel model = (DefaultTableModel) jtLivros.getModel();

        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        Object rowData[] = new Object[7];//define vetor das colunas

        for (livro listLiv : cadLiv.getLivros()) {
            rowData[0] = listLiv.getTitulo();
            rowData[1] = listLiv.getIsbn();
            rowData[2] = listLiv.getAutor();
            rowData[3] = listLiv.getAssunto();
            rowData[4] = listLiv.getEstoque();
            rowData[5] = cadEdi.pesqNomeEditora(listLiv.getIdEditora());
            rowData[6] = listLiv.getPreco();

            model.addRow(rowData);

        }
    }


    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        jtfTitulo.setText("");
        //jcbEditora.addItem("Selecione");
        jtfAutor.setText("");
        jtfIsbn.setText("");
        jtfQntd.setText("");
        jtfPreco.setText("");
        jtfAssunto.setText("");
        jtfTitulo.requestFocus();
    }//GEN-LAST:event_jbLimparActionPerformed

    public void addItemEditora() {
        jcbEditora.addItem("Selecione");
        for (editora editora : cadEdi.getEditoras()) {
            jcbEditora.addItem(editora.getNomeEditora());
        }
    }

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // TODO add your handling code here:
        livro l = new livro();
        byte i = 1;
        String erros[] = new String[6];
        boolean validaEditora = false, validaTitulo = false, validaAutor = false, validaIsbn = false, validaAssunto = false, validaQntd = false, validaPreco = false;

        if (!jtfTitulo.getText().equals("")) {
            l.setTitulo(jtfTitulo.getText());
            validaTitulo = true;
        } else {
            erros[i] = "Título não pode ser em branco";
            i++;
        }

        if (!jtfAutor.getText().equals("")) {
            l.setAutor(jtfAutor.getText());
            validaAutor = true;
        } else {
            erros[i] = "Autor não pode ser em branco";
            i++;
        }

        if (!jtfAssunto.getText().equals("")) {
            l.setAssunto(jtfAssunto.getText());
            validaAssunto = true;
        } else {
            erros[i] = "Assunto não pode ser em branco";
            i++;
        }

        if (!jtfIsbn.getText().equals("")) {
            l.setIsbn(jtfIsbn.getText());
            validaIsbn = true;
        } else {
            erros[i] = "ISBN não pode ser em branco";
            i++;
        }

        if (!jtfQntd.getText().equals("")) {
            l.setEstoque(Integer.parseInt(jtfQntd.getText()));
            validaQntd = true;
        } else {
            erros[i] = "Quantidade não pode ser em branco";
            i++;
        }

        if (!jtfPreco.getText().equals("")) {
            l.setPreco(Float.parseFloat(jtfPreco.getText()));
            validaPreco = true;
        } else {
            erros[i] = "Preço não pode ser em branco";
            i++;
        }

        if (!jcbEditora.getSelectedItem().toString().equals("Selecione")) {
            l.setIdLivro(cadEdi.addEditoraCB(jcbEditora.getSelectedItem().toString()));
            validaEditora = true;
            if (validaTitulo && validaAutor && validaAssunto && validaIsbn && validaPreco && validaQntd && validaEditora) {
                cadLiv.addLivro(l);
                JOptionPane.showMessageDialog(this, "Livro cadastrado com sucesso!");
                
            }
        } else {
            JOptionPane.showMessageDialog(this, "Primeiro selecione a editora", "Erro", ERROR);
        }


    }//GEN-LAST:event_jbSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcbEditora;
    private javax.swing.JLabel jlAssunto;
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlIsbn;
    private javax.swing.JLabel jlPreco;
    private javax.swing.JLabel jlQntd;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable jtLivros;
    private javax.swing.JTextField jtfAssunto;
    private javax.swing.JTextField jtfAutor;
    private javax.swing.JTextField jtfIsbn;
    private javax.swing.JTextField jtfPreco;
    private javax.swing.JTextField jtfQntd;
    private javax.swing.JTextField jtfTitulo;
    // End of variables declaration//GEN-END:variables

}
